BadHomburgBlog/Controllers/BlogEntryController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using BadHomburgBlog.Data;
using BadHomburgBlog.DomainModels;
using BadHomburgBlog.ViewModels;

namespace BadHomburgBlog.Controllers
{
    public class BlogEntryController : Controller
    {
        //
        // GET: /BlogEntry/

        public ActionResult Show(string date, string title)
        {
            DateTime blogDate = DateTime.ParseExact(date, "yyyyMMdd", CultureInfo.InvariantCulture);
            using (var dbContext = new BlogDbContext()){
                var query = from be in dbContext.BlogEntries
                            where be.Title == title &&
                                  be.Date == blogDate
                            select be;
                var model = query.Single().MapFrom<BlogEntry, BlogEntryModel>();
                return View(model);
            }
        }

        [Authorize]
        public ActionResult Create(int id)
        {
            return View(new BlogEntryModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(int id, BlogEntryModel model)
        {
            if (ModelState.IsValid){
                using (var dbContext = new BlogDbContext()){
                    var blog = dbContext.Blogs.Single(b => b.Id == id);
                    var blogEntry = new BlogEntry();
                    blogEntry.Author = GetCurrentWebUser(dbContext);
                    model.MapTo(blogEntry);
                    blog.BlogEntries.Add(blogEntry);
                    dbContext.SaveChanges();
                }
                return RedirectToAction("Details", "Blog", new {id = id});
            }
            return View(model);
        }

        private WebUser GetCurrentWebUser(BlogDbContext dbContext)
        {
            return dbContext.Users.Single(u => u.Name == User.Identity.Name);
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            using (var dbContext = new BlogDbContext()){
                var model = dbContext.BlogEntries.Single(be => be.Id == id).MapFrom<BlogEntry, BlogEntryModel>();
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(int id, BlogEntryModel model)
        {
            if (ModelState.IsValid){
                using (var dbContext = new BlogDbContext()){
                    var blogEntry = dbContext.BlogEntries.Single(be => be.Id == id);
                    model.MapTo(blogEntry);
                    dbContext.SaveChanges();
                }
                return RedirectToShow(model);
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment(int id, CommentModel model)
        {
            using (var dbContext = new BlogDbContext()){
                var blogEntry = dbContext.BlogEntries.Single(be => be.Id == id);
                if (ModelState.IsValid){
                    var newComment = model.MapFrom<CommentModel, Comment>();
                    blogEntry.Comments.Add(newComment);
                    dbContext.SaveChanges();
                    return RedirectToShow(blogEntry.MapFrom<BlogEntry, BlogEntryModel>());
                }
                return View("Show", blogEntry.MapFrom<BlogEntry, BlogEntryModel>());
            }
        }

        private ActionResult RedirectToShow(BlogEntryModel model)
        {
            return RedirectToAction("Show", new {date = model.Date.ToString("yyyyMMdd"), title = model.Title});
        }
    }
}

BadHomburgBlog/Views/BlogEntry/AddComment.cshtml
@model BadHomburgBlog.ViewModels.CommentModel

@using (Html.BeginForm("AddComment","BlogEntry",new {id=ViewData["EntryId"]},FormMethod.Post,null)) {
    @Html.AntiForgeryToken();
     @Html.LabelFor(m => m.Name)   @Html.TextBoxFor(m=>m.Name) @Html.ValidationMessageFor(m=>m.Name)<br />

     @Html.LabelFor(m => m.Text)  @Html.ValidationMessageFor(m => m.Text)<br />
     @Html.TextAreaFor(m => m.Text)<br />
    <button type="submit">Kommentar absenden</button>
}

BadHomburgBlog/Views/BlogEntry/Create.cshtml
@model BadHomburgBlog.ViewModels.BlogEntryModel

@{
    ViewBag.Title = "Neuen Eintrag anlegen";
}

<h2>Neuen Eintrag anlegen</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Fields</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Text)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Text)
            @Html.ValidationMessageFor(model => model.Text)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


BadHomburgBlog/Views/BlogEntry/Edit.cshtml
@model BadHomburgBlog.ViewModels.BlogEntryModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Fields</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Text)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Text)
            @Html.ValidationMessageFor(model => model.Text)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


BadHomburgBlog/Views/BlogEntry/Show.cshtml
@model BadHomburgBlog.ViewModels.BlogEntryModel

@{
    ViewBag.Title = Model.Title;
    ViewData["EntryId"]=Model.Id;
}

<h2>@Model.Title</h2>
<h3>@Model.Date.ToLongDateString()</h3>
<p>@Model.Text</p>

<h3>Kommentare</h3>
@foreach (var comment in Model.Comments)
{
        @Html.Partial("ShowComment", comment);
}

<h3>Kommentar hinzufügen</h3>
@Html.Partial("AddComment", new BadHomburgBlog.ViewModels.CommentModel())

<p>
@Html.ActionLink("Eintrag bearbeiten", "Edit", "BlogEntry", new { Model.Id }, null)
</p>

BadHomburgBlog/Views/BlogEntry/ShowComment.cshtml
@model BadHomburgBlog.ViewModels.CommentModel

    <div class="display-label"><b>Name:</b></div>
    <div class="display-field">@Model.Name</div>

    <div class="display-label"><b>Text:</b></div>
    <div class="display-field">@Model.Text</div>
<hr />